# Development configuration template
# Run ./setup_dev.sh to copy this to server/application_dev.conf

chefgpt {
    storage = "database" # or "memory" if you don't want to run your own servers
    agent = "fake" # or "llm" if you want to provide your own anthropic key
    imageUploader = "fake" # or "cloudinary" if you want to provide your own cloudinary credentials
    anthropicApiKey = "<your-api-key>"
    spoonacularApiKey = "<your-api-key>"
    cloudinary {
        apiKey = "<your-api-key>"
        apiSecret = "<your-api-secret>"
        cloud = "<your-cloud>"
    }
}

postgres {
    host = "localhost"
    port = 5432
    database = "chefgpt"
    username = "postgres"
}

rethinkdb {
    host = "localhost"
    port = 28015
    database = "chefgpt"
}
