package se.gustavkarlsson.chefgpt.ingredients

/**
 * A curated, hard-coded catalog of real food ingredients used to autocomplete the ingredient input.
 *
 * Names are stored lowercase and alphabetically so [match] only needs a single linear substring scan, which is
 * cheap for a list of this size and runs comfortably on every keystroke.
 *
 * Small items you'd likely use several of are plural (e.g. "apples", "eggs"); large "one of" items and
 * uncountable (mass) ingredients like spices, oils and flour stay singular.
 */
object IngredientWords {
    /**
     * Case-insensitive substring match: every ingredient whose name contains [query]. Names that *start* with
     * [query] are ranked before mid-word matches; both groups keep the catalog's alphabetical order. Capped at
     * [limit]. A blank [query] yields no matches.
     */
    fun match(
        query: String,
        limit: Int = 12,
    ): List<String> {
        val needle = query.trim().lowercase()
        if (needle.isEmpty()) return emptyList()
        val (prefix, contains) =
            all
                .filter { it.contains(needle) }
                .partition { it.startsWith(needle) }
        return (prefix + contains).take(limit)
    }

    val all: List<String> =
        listOf(
            "almonds",
            "anchovies",
            "apples",
            "apricots",
            "artichokes",
            "arugula",
            "asparagus",
            "aubergine",
            "avocados",
            "bacon",
            "baking powder",
            "baking soda",
            "balsamic vinegar",
            "bananas",
            "barley",
            "basil",
            "bay leaf",
            "beans",
            "beef",
            "beets",
            "bell peppers",
            "black beans",
            "black pepper",
            "blackberries",
            "blueberries",
            "bok choy",
            "bread",
            "breadcrumbs",
            "broccoli",
            "broth",
            "brown sugar",
            "brussels sprouts",
            "buckwheat",
            "bulgur",
            "butter",
            "buttermilk",
            "cabbage",
            "cantaloupe",
            "cardamom",
            "carrots",
            "cashews",
            "cauliflower",
            "cayenne",
            "celery",
            "chard",
            "cheese",
            "cherries",
            "chia seeds",
            "chicken",
            "chickpeas",
            "chilies",
            "chives",
            "cilantro",
            "cinnamon",
            "clams",
            "clementines",
            "cloves",
            "cocoa",
            "coconut",
            "cod",
            "coffee",
            "coriander",
            "corn",
            "cornstarch",
            "courgettes",
            "couscous",
            "crab",
            "cranberries",
            "cream",
            "cream cheese",
            "cucumbers",
            "cumin",
            "dates",
            "dill",
            "duck",
            "eggplant",
            "eggs",
            "endive",
            "fennel",
            "fenugreek",
            "feta",
            "figs",
            "flaxseed",
            "flour",
            "garlic",
            "ghee",
            "ginger",
            "grapefruit",
            "grapes",
            "green beans",
            "guavas",
            "ham",
            "hazelnuts",
            "honey",
            "honey mustard",
            "juice",
            "kale",
            "ketchup",
            "kidney beans",
            "kiwis",
            "lamb",
            "leeks",
            "lemons",
            "lentils",
            "lettuce",
            "limes",
            "lobster",
            "lychees",
            "mangoes",
            "maple syrup",
            "mayonnaise",
            "melon",
            "milk",
            "mint",
            "molasses",
            "mozzarella",
            "mushrooms",
            "mussels",
            "mustard",
            "nectarines",
            "noodles",
            "nutmeg",
            "oats",
            "okra",
            "olive oil",
            "olives",
            "onions",
            "oranges",
            "oregano",
            "oysters",
            "papaya",
            "paprika",
            "parmesan",
            "parsley",
            "parsnips",
            "passion fruits",
            "pasta",
            "peaches",
            "peanuts",
            "pears",
            "peas",
            "pecans",
            "pepper",
            "persimmons",
            "pine nuts",
            "pineapple",
            "pistachios",
            "plums",
            "polenta",
            "pomegranate",
            "pork",
            "potatoes",
            "prawns",
            "prunes",
            "pumpkin",
            "pumpkin seeds",
            "quinoa",
            "radishes",
            "raisins",
            "raspberries",
            "rhubarb",
            "rice",
            "ricotta",
            "rosemary",
            "saffron",
            "sage",
            "salmon",
            "sardines",
            "sausages",
            "scallions",
            "scallops",
            "sesame",
            "shallots",
            "shrimp",
            "sour cream",
            "soy sauce",
            "spaghetti",
            "spinach",
            "squash",
            "squid",
            "steak",
            "stock",
            "strawberries",
            "sugar",
            "sunflower seeds",
            "sweet potatoes",
            "tangerines",
            "tarragon",
            "tea",
            "thyme",
            "tomato paste",
            "tomato sauce",
            "tomatoes",
            "tortillas",
            "tuna",
            "turkey",
            "turmeric",
            "turnips",
            "vanilla",
            "vegetable oil",
            "vinegar",
            "walnuts",
            "watermelon",
            "wheat",
            "yams",
            "yeast",
            "yogurt",
            "zucchini",
        )
}
