ktor {
    deployment {
        port = 80
        port = ${?PORT} // Overrides default port if set
    }
    application {
        modules = ["se.gustavkarlsson.chefgpt.ApplicationKt.module"]
    }
}

chefgpt {
    storage = "database"
    storage = ${?STORAGE}
    anthropicApiKey = ${?ANTHROPIC_API_KEY}
    spoonacularApiKey = ${?SPOONACULAR_API_KEY}
    ingredientStoreRootDir = ${?INGREDIENT_STORE_ROOT_DIR}
    cloudinary {
        apiKey = ${?CLOUDINARY_API_KEY}
        apiSecret = ${?CLOUDINARY_API_SECRET}
        cloud = ${?CLOUDINARY_CLOUD}
    }
}

database {
    host = ${?DB_HOST}
    port = ${?DB_PORT}
    name = ${?DB_NAME}
    username = ${?DB_USERNAME}
    password = ${?DB_PASSWORD}
}

include file("application_dev.conf") // Create and set development config
