ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = ["se.gustavkarlsson.chefgpt.ApplicationKt.module"]
    }
}

bindings {
    storage = "database" # or "memory"
    storage = ${?STORAGE}
    recipes = "spoonacular" # or "fake"
    recipes = ${?RECIPES}
    agent = "llm" # or "fake"
    agent = ${?AGENT}
    imageUploader = "cloudinary" # or "fake"
    imageUploader = ${?IMAGE_UPLOADER}
}

anthropic {
    apiKey = ${?ANTHROPIC_API_KEY}
}

spoonacular {
    apiKey = ${?SPOONACULAR_API_KEY}
}

cloudinary {
    apiKey = ${?CLOUDINARY_API_KEY}
    apiSecret = ${?CLOUDINARY_API_SECRET}
    cloud = ${?CLOUDINARY_CLOUD}
}

logging {
    calls {
        request {
            headers = false
        }
        response {
            headers = false
        }
    }
}

postgres {
    host = ${?POSTGRES_HOST}
    port = ${?POSTGRES_PORT}
    database = ${?POSTGRES_DATABASE}
    username = ${?POSTGRES_USERNAME}
    password = ${?POSTGRES_PASSWORD}
}

include file("application_dev.conf")
