ktor {
    deployment {
        port = 8080
        port = ${?PORT} // Overrides default port if set
    }
    application {
        modules = ["se.gustavkarlsson.chefgpt.ApplicationKt.module"]
    }
}

chefgpt {
    anthropicApiKey = "<missing>"
    anthropicApiKey = ${?ANTHROPIC_API_KEY}
    spoonacularApiKey = "<missing>"
    spoonacularApiKey = ${?SPOONACULAR_API_KEY}
    cloudinary {
        apiKey = "<missing>"
        apiKey = ${?CLOUDINARY_API_KEY}
        apiSecret = "<missing>"
        apiSecret = ${?CLOUDINARY_API_SECRET}
        cloud = "<missing>"
        cloud = ${?CLOUDINARY_CLOUD}
    }
}

logging {
    calls {
        request {
            headers = false
        }
        response {
            headers = false
        }
    }
}

postgres {
    host = "localhost"
    host = ${?POSTGRES_HOST}
    port = 5432
    port = ${?POSTGRES_PORT}
    database = "chefgpt"
    database = ${?POSTGRES_DATABASE}
    username = "postgres"
    username = ${?POSTGRES_USERNAME}
    password = ${?POSTGRES_PASSWORD}
}

rethinkdb {
    host = "localhost"
    host = ${?RETHINKDB_HOST}
    port = 28015
    port = ${?RETHINKDB_PORT}
    database = "chefgpt"
    database = ${?RETHINKDB_DB}
    username = ${?RETHINKDB_USERNAME}
    password = ${?RETHINKDB_PASSWORD}
}

include file("application_dev.conf") // Create and set development config
