package se.gustavkarlsson.chefgpt.api

import kotlinx.serialization.Serializable
import kotlin.time.Instant
import kotlin.uuid.Uuid

/**
 * An event is something that has happened in a chat.
 */
@Serializable
sealed interface ApiEvent {
    val id: Uuid
    val timestamp: Instant
}

/**
 * Events generated by the system
 */
@Serializable
sealed interface ApiSystemEvent : ApiEvent

/**
 * Events generated by an agent
 */
@Serializable
sealed interface ApiAgentEvent : ApiEvent

/**
 * Events generated by a user, typically as the result of an [ApiAction]
 */
@Serializable
sealed interface ApiUserEvent : ApiEvent

@Serializable
data class ApiAgentMessage(
    override val id: Uuid,
    override val timestamp: Instant,
    val text: String,
) : ApiAgentEvent {
    init {
        require(text.isNotBlank()) {
            "Text must not be blank"
        }
    }
}

@Serializable
data class ApiAgentReasoning(
    override val id: Uuid,
    override val timestamp: Instant,
    val text: String,
) : ApiAgentEvent {
    init {
        require(text.isNotBlank()) {
            "Text must not be blank"
        }
    }
}

@Serializable
data class ApiUserMessage(
    override val id: Uuid,
    override val timestamp: Instant,
    val text: String?,
    val imageUrl: ImageUrl? = null,
) : ApiUserEvent {
    init {
        require(text == null || text.isNotBlank()) {
            "Text must not be blank"
        }
        require(text != null || imageUrl != null) {
            "Message must contain text or imageUrl"
        }
    }
}
