name: Cache Cleanup

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  delete-cache:
    name: Delete branch-local Gradle cache
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete cache for this PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh cache delete --all
          --ref refs/pull/${{ github.event.pull_request.number }}/merge
          --succeed-on-no-caches
          --repo ${{ github.repository }}
